# Default values for linkwarden.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# -- This will set the replicaset count more information can be found here: https://kubernetes.io/docs/concepts/workloads/controllers/replicaset/
# If you want to create a HA setup with more than one replica you have to disable persistence and use S3 storage instead
replicaCount: 1

# -- Linkwarden specific settings
linkwarden:
  # -- Postgres connection settings
  postgres:
    # -- Required. Name of a secret that contains postgres connection settings. Secret must contain a field 'uri'
    existingSecret: ~
  # -- Settings for meilisearch integration
  meilisearch:
    # -- Host address for meilisearch. If left empty meilisearch integration will be disabled
    host: ~
    # -- Existing secret for the meilisearch master key. Must contain 'master-key' field. Required when host is set
    existingSecret: ~
    # -- Timeout for a meilisearch search
    timeout: 1000000

  # -- Authentication settings for linkwarden
  auth:
    # -- Required. Name of a secret containing a secret string to be used for the authentication mechanism. Secret must contain 'auth-secret' field
    existingSecret: ~
    # -- If set to true, registration will be disabled.
    disableRegistration: false
    # -- If set to true, users won't be able to login with username and password.
    disableCredentialLogin: false
    # -- If set to true, new users will not be able to login with SSO.
    disableNewSSOLogins: false
    # -- Id of the admin user. Defaults to the first user registered
    adminUserId: 1
    # -- Settings for authentik
    authentik:
      # -- Set to true to enable authentik
      enabled: false
      # -- OpenID configuration issuer for the application
      issuer: ~
      # -- Client ID of the authentik application
      clientId: ~
      # -- Existing kubernetes secret containing the client secret of the authentik application. Requires a 'client-secret' value
      existingSecret: ~
      # -- Optional custom provider name
      customName: ~

  # -- The numbers of Links to fetch every time you reach the bottom of the webpage
  paginationTakeCount: 50
  # -- The amount of time to wait for the website to be archived (in seconds).
  autoscrollTimeout: 30
  # -- Adjusts how often a user can trigger a new archive for each link (in minutes).
  reArchiveLimit: 5
  # -- Limits the maximum number of links per user
  maxLinksPerUser: 30000
  # -- Set to true to allow processing of insecure links
  allowInsecureLinks: false
  # -- Set to true to ignore header size limit when fetching links
  ignoreUrlSizeLimit: ~
  # -- Maximum size in MB of a link preview
  maxPreviewSize: 10
  # -- Maximum size in MB for a imported link
  maxImportSize: 10
  # -- Set to true if you want to disable all preservation mechanisms
  disablePreservation: false
  # -- Polling interval in minutes for rss feeds
  rssPollingInterval: 60
  # -- Maximum of rss subscriptions per user
  rssSubscriptionLimitPerUser: 20
  # -- Limits the number of filters that can be used in search
  searchFilterLimit: ~
  # -- Number of links that will be indexed at a time
  indexAmount: 50

  # -- Settings for the preservation process
  preservationSettings:
    # -- Number of links that will be archived in the background
    worker: 5
    # -- Timeout in minutes after which the archive process will be stopped
    timeout: 5
    # -- Maximum size in MB a link archive can have
    maxFileSize: 10
    # -- Maximum size in MB a pdf copy of a link can have
    maxPdfSize: 100
    # -- Maximum size in MB a screenshot of a link can have
    maxScreenshotSize: 100
    # -- Maximum size in MB a readability version of a link can have
    maxReadabilitySize: 100
    # -- Maximum size in MB the monolith (see: https://github.com/Y2Z/monolith) version of a link can have
    maxMonolithSize: 100
    # -- If set limits the amount of text for a readability version of a link
    readabilityTextLimit: ~

  # -- Custom options for the monolith process
  monolithCustomOptions: ~

deployment:
  kind: StatefulSet

# -- Additional env values to pass to the container
env: {}
# - name: TZ
#   value: Europe/Berlin

# -- This sets the container image more information can be found here: https://kubernetes.io/docs/concepts/containers/images/
image:
  # -- The registry where the image is hosted
  registry: docker.io
  # -- Repository of the image
  repository: denniswitt/linkwarden-rootless
  # -- This sets the pull policy for images.
  pullPolicy: IfNotPresent
  # -- Overrides the image tag whose default is the chart appVersion.
  tag: ""

# -- This is for the secretes for pulling an image from a private repository more information can be found here: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
imagePullSecrets: []
# -- This is to override the chart name.
nameOverride: ""
fullnameOverride: ""

# -- This section builds out the service account more information can be found here: https://kubernetes.io/docs/concepts/security/service-accounts/
serviceAccount:
  # -- Specifies whether a service account should be created
  create: true
  # -- Automatically mount a ServiceAccount's API credentials?
  automount: false
  # -- Annotations to add to the service account
  annotations: {}
  # -- The name of the service account to use.
  # -- If not set and create is true, a name is generated using the fullname template
  name: ""

# -- This is for setting Kubernetes Annotations to a Pod.
# For more information checkout: https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/
podAnnotations: {}
# -- This is for setting Kubernetes Labels to a Pod.
# For more information checkout: https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/
podLabels: {}

podSecurityContext:
  runAsNonRoot: true
  runAsUser: 1000
  runAsGroup: 1000
  fsGroup: 1000
  fsGroupChangePolicy: OnRootMismatch
  seccompProfile:
    type: RuntimeDefault

securityContext:
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true
  seccompProfile:
    type: RuntimeDefault
  runAsUser: 1000
  runAsGroup: 1000
  runAsNonRoot: true
  privileged: false
  capabilities:
    drop:
      - ALL

# -- This is for setting up a service more information can be found here: https://kubernetes.io/docs/concepts/services-networking/service/
service:
  # -- This sets the service type more information can be found here: https://kubernetes.io/docs/concepts/services-networking/service/#publishing-services-service-types
  type: ClusterIP
  # -- This sets the ports more information can be found here: https://kubernetes.io/docs/concepts/services-networking/service/#field-spec-ports
  port: 80

# -- This block is for setting up the ingress for more information can be found here: https://kubernetes.io/docs/concepts/services-networking/ingress/
ingress:
  enabled: false
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

# -- Block for setting up gateway api http route. More information can be found here: https://gateway-api.sigs.k8s.io/
route:
  # -- Flag to control if route should be created
  enabled: false
  # -- Additional labels for the HTTPRoute
  labels: {}
  # -- Additional annotations for the HTTPRoute
  annotations: {}
  # -- Hostnames of the HTTPRoute
  hostnames: []
  # - linkwarden.example.com
  # - links.example.com

  # -- Gateway reference that the HTTPRoute should bind against
  parentRefs: []
  # - group: gateway.networking.k8s.io
  #   kind: Gateway
  #   name: example-gateway
  #   namespace: gateway-namespace

  # -- Matches for the default rule
  matches:
    - path:
        type: PathPrefix
        value: /

  # -- Filter that should be added to the default rule
  filters: []

  # -- Any custom rule you want to specify
  additionalRules: {}

# -- Settings for storage
persistence:
  # -- If persistent volumes should be configured. Disable preservation features when you set this to false
  enabled: true
  # -- Storage class to use for persistent storage. If left empty default storage class will be used.
  storageClass: ~
  # -- Size for the persistent volume claim.
  size: 10Gi
  # -- Use this if you're deploying as DaemonSet
  hostPath: ~

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

# -- This is to setup the liveness and readiness probes more information can be found here: https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/
livenessProbe:
  httpGet:
    path: /
    port: http
readinessProbe:
  httpGet:
    path: /
    port: http

# -- Additional volumes on the output Deployment definition.
volumes: []
# - name: foo
#   secret:
#     secretName: mysecret
#     optional: false

# -- Additional volumeMounts on the output Deployment definition.
volumeMounts: []
# - name: foo
#   mountPath: "/etc/foo"
#   readOnly: true

nodeSelector: {}

tolerations: []

affinity: {}
